services:
  solid-todo:
    build: solid-todo
    container_name: solid-todo
    networks:
      - app-network

  nginx:
    image: nginx:1.27.3-alpine
    container_name: reverse-proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network: